### ISSUE TITLE
illegal instruction after 20170904 update on KVM

### ISSUE THREAD

**Issue by IndeedPlusPlus** [xtaci/kcptun#512]
server is Debian 9 on KVM, guest is using QEMU virtual CPU for easy hot migration.
```
cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version (cpu64-rhel6)
stepping        : 3
microcode       : 0x1
cpu MHz         : 1999.965
cache size      : 4096 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 4
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm nopl eagerfpu pni cx16 hypervisor lahf_lm
bugs            :
bogomips        : 3999.93
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

It seens that AVX instrction is not supported.

```
 ./server_linux_amd64 -l :5353 -t 127.0.0.1:8388 --crypt none --mtu 1200 --nocomp --mode normal --dscp 46                                                                                        
2017/09/29 22:40:49 version: 20170904
2017/09/29 22:40:49 listening on: [::]:5353
2017/09/29 22:40:49 target: 127.0.0.1:8388
2017/09/29 22:40:49 encryption: none
2017/09/29 22:40:49 nodelay parameters: 0 40 2 1
2017/09/29 22:40:49 sndwnd: 1024 rcvwnd: 1024
2017/09/29 22:40:49 compression: false
2017/09/29 22:40:49 mtu: 1200
2017/09/29 22:40:49 datashard: 10 parityshard: 3
2017/09/29 22:40:49 acknodelay: false
2017/09/29 22:40:49 dscp: 46
2017/09/29 22:40:49 sockbuf: 4194304
2017/09/29 22:40:49 keepalive: 10
2017/09/29 22:40:49 snmplog:
2017/09/29 22:40:49 snmpperiod: 60
2017/09/29 22:40:49 pprof: false
2017/09/29 22:41:03 remote address: 127.0.0.1:59380
2017/09/29 22:41:03 stream opened
2017/09/29 22:41:03 stream closed
2017/09/29 22:41:07 stream opened
2017/09/29 22:41:08 stream closed
2017/09/29 22:41:09 stream opened
SIGILL: illegal instruction
PC=0x71850f m=2 sigcode=2

goroutine 6 [running]:
github.com/templexxx/reedsolomon.mulVectAVX2(0xc42008d000, 0x20, 0x3c0, 0xc42001381a, 0x270, 0x5c2, 0xc42012b81a, 0x270, 0x5c2, 0x3c0, ...)
        /Users/xtaci/src/github.com/templexxx/reedsolomon/rs_amd64.s:44 +0xf fp=0xc42003d9e8 sp=0xc42003d9e0 pc=0x71850f
github.com/templexxx/reedsolomon.(*encAVX2).matrixMul(0xc4201201b0, 0x0, 0x270, 0xc420010b40, 0xa, 0xd, 0xc420010c30, 0x3, 0x3)
        /Users/xtaci/src/github.com/templexxx/reedsolomon/rs_amd64.go:144 +0x2a0 fp=0xc42003da80 sp=0xc42003d9e8 pc=0x710fe0
github.com/templexxx/reedsolomon.(*encAVX2).Encode(0xc4201201b0, 0xc420010b40, 0xd, 0xd, 0x257, 0x5a8)
        /Users/xtaci/src/github.com/templexxx/reedsolomon/rs_amd64.go:117 +0x1c0 fp=0xc42003db20 sp=0xc42003da80 pc=0x710c80
github.com/xtaci/kcp-go.(*fecEncoder).encode(0xc4200f4480, 0xc42012cc00, 0x34, 0x5dc, 0x45d856, 0x1ba515, 0x152d41f7)
        /Users/xtaci/src/github.com/xtaci/kcp-go/fec.go:277 +0x338 fp=0xc42003dba8 sp=0xc42003db20 pc=0x7261f8
github.com/xtaci/kcp-go.(*UDPSession).output(0xc42006f0e0, 0xc420071000, 0x18, 0xe04)
        /Users/xtaci/src/github.com/xtaci/kcp-go/sess.go:472 +0x554 fp=0xc42003dc58 sp=0xc42003dba8 pc=0x72c814
github.com/xtaci/kcp-go.newUDPSession.func1(0xc420071000, 0xe04, 0xe04, 0x18)
        /Users/xtaci/src/github.com/xtaci/kcp-go/sess.go:150 +0x53 fp=0xc42003dc88 sp=0xc42003dc58 pc=0x731d73
github.com/xtaci/kcp-go.(*KCP).flush(0xc42006f200, 0x0)
        /Users/xtaci/src/github.com/xtaci/kcp-go/kcp.go:802 +0xb0a fp=0xc42003de40 sp=0xc42003dc88 pc=0x72939a
github.com/xtaci/kcp-go.(*UDPSession).update(0xc42006f0e0, 0x4b63a35b5)
        /Users/xtaci/src/github.com/xtaci/kcp-go/sess.go:513 +0x54 fp=0xc42003de70 sp=0xc42003de40 pc=0x72c8f4
github.com/xtaci/kcp-go.(*updateHeap).updateTask(0xa3f320)
        /Users/xtaci/src/github.com/xtaci/kcp-go/updater.go:92 +0x47 fp=0xc42003dfd8 sp=0xc42003de70 pc=0x731497
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42003dfe0 sp=0xc42003dfd8 pc=0x45c781
created by github.com/xtaci/kcp-go.init.2
        /Users/xtaci/src/github.com/xtaci/kcp-go/updater.go:13 +0x74

goroutine 1 [select]:
github.com/xtaci/kcp-go.(*Listener).AcceptKCP(0xc4200f4280, 0x8259a0, 0x9eedc0, 0xc42006f0e0)
        /Users/xtaci/src/github.com/xtaci/kcp-go/sess.go:817 +0x233
main.main.func1(0xc4200906e0, 0x0, 0x0)
        /Users/xtaci/src/github.com/xtaci/kcptun/server/main.go:362 +0x1898
github.com/urfave/cli.HandleAction(0x788800, 0x8259a8, 0xc4200906e0, 0xc42004a240, 0x0)
        /Users/xtaci/src/github.com/urfave/cli/app.go:490 +0xd2
github.com/urfave/cli.(*App).Run(0xc4200629c0, 0xc42000e0e0, 0xe, 0xe, 0x0, 0x0)
        /Users/xtaci/src/github.com/urfave/cli/app.go:264 +0x635
main.main()
        /Users/xtaci/src/github.com/xtaci/kcptun/server/main.go:381 +0x1243

goroutine 10 [select]:
github.com/xtaci/kcp-go.(*Listener).monitor(0xc4200f4280)
        /Users/xtaci/src/github.com/xtaci/kcp-go/sess.go:694 +0x20a
created by github.com/xtaci/kcp-go.ServeConn
        /Users/xtaci/src/github.com/xtaci/kcp-go/sess.go:904 +0x21d

goroutine 7 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 8 [chan receive]:
main.sigHandler()
        /Users/xtaci/src/github.com/xtaci/kcptun/server/signal.go:24 +0x109
created by main.init.0
        /Users/xtaci/src/github.com/xtaci/kcptun/server/signal.go:15 +0x35

goroutine 9 [select, locked to thread]:
runtime.gopark(0x826140, 0x0, 0x80ad50, 0x6, 0x18, 0x1)
        /usr/local/go/src/runtime/proc.go:277 +0x12c
runtime.selectgo(0xc420040f50, 0xc4200543c0)
        /usr/local/go/src/runtime/select.go:395 +0x1138
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 12 [IO wait]:
internal/poll.runtime_pollWait(0x7ff74cac1f70, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4200f4218, 0x72, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc4200f4218, 0xc4201a1800, 0x5dc, 0x5dc)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).ReadFrom(0xc4200f4200, 0xc4201a1800, 0x5dc, 0x5dc, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x19a
net.(*netFD).readFrom(0xc4200f4200, 0xc4201a1800, 0x5dc, 0x5dc, 0xc420042f58, 0x2, 0x2, 0xc420042e08, 0x40e87e)
        /usr/local/go/src/net/fd_unix.go:208 +0x5e
net.(*UDPConn).readFrom(0xc42000c070, 0xc4201a1800, 0x5dc, 0x5dc, 0xc420042ea8, 0x46549b, 0x777b00, 0xc4201b4640)
        /usr/local/go/src/net/udpsock_posix.go:47 +0x6a
net.(*UDPConn).ReadFrom(0xc42000c070, 0xc4201a1800, 0x5dc, 0x5dc, 0x108, 0x9ed180, 0xc42005bb30, 0x0, 0x0)
        /usr/local/go/src/net/udpsock.go:118 +0x72
github.com/xtaci/kcp-go.(*Listener).receiver(0xc4200f4280, 0xc42004a5a0)
        /Users/xtaci/src/github.com/xtaci/kcp-go/sess.go:767 +0xa7
created by github.com/xtaci/kcp-go.(*Listener).monitor
        /Users/xtaci/src/github.com/xtaci/kcp-go/sess.go:692 +0x82

goroutine 13 [select]:
github.com/xtaci/smux.(*Session).AcceptStream(0xc4200f4500, 0x0, 0x0, 0x0)
        /Users/xtaci/src/github.com/xtaci/smux/session.go:125 +0x260
main.handleMux(0x9eedc0, 0xc42006f0e0, 0xc420110000)
        /Users/xtaci/src/github.com/xtaci/kcptun/server/main.go:73 +0x16e
created by main.main.func1
        /Users/xtaci/src/github.com/xtaci/kcptun/server/main.go:372 +0x1aeb

goroutine 14 [select]:
github.com/xtaci/kcp-go.(*UDPSession).Read(0xc42006f0e0, 0xc420140000, 0x8, 0x10008, 0x404050, 0xc420054d18, 0xc420054cc0)
        /Users/xtaci/src/github.com/xtaci/kcp-go/sess.go:229 +0x2c1
io.ReadAtLeast(0x7ff74cac2260, 0xc42006f0e0, 0xc420140000, 0x8, 0x10008, 0x8, 0x7f9ec0, 0xc42003ee00, 0x7ff74cac2260)
        /usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x7ff74cac2260, 0xc42006f0e0, 0xc420140000, 0x8, 0x10008, 0x736e9c, 0x1, 0xc42003ee78)
        /usr/local/go/src/io/io.go:327 +0x58
github.com/xtaci/smux.(*Session).readFrame(0xc4200f4500, 0xc420140000, 0x10008, 0x10008, 0x700010201, 0xc420140008, 0xc4, 0x10000, 0x0, 0x0)
        /Users/xtaci/src/github.com/xtaci/smux/session.go:213 +0x91
github.com/xtaci/smux.(*Session).recvLoop(0xc4200f4500)
        /Users/xtaci/src/github.com/xtaci/smux/session.go:242 +0xfa
created by github.com/xtaci/smux.newSession
        /Users/xtaci/src/github.com/xtaci/smux/session.go:76 +0x1d5

goroutine 15 [select]:
github.com/xtaci/smux.(*Session).sendLoop(0xc4200f4500)
        /Users/xtaci/src/github.com/xtaci/smux/session.go:308 +0x178
created by github.com/xtaci/smux.newSession
        /Users/xtaci/src/github.com/xtaci/smux/session.go:77 +0x1f7

goroutine 16 [select]:
github.com/xtaci/smux.(*Session).keepalive(0xc4200f4500)
        /Users/xtaci/src/github.com/xtaci/smux/session.go:290 +0x1c9
created by github.com/xtaci/smux.newSession
        /Users/xtaci/src/github.com/xtaci/smux/session.go:78 +0x219

goroutine 27 [select]:
main.handleClient(0x9eee00, 0xc4200f6240, 0x7ff74cac6288, 0xc42000c0a0)
        /Users/xtaci/src/github.com/xtaci/kcptun/server/main.go:102 +0x2cb
created by main.handleMux
        /Users/xtaci/src/github.com/xtaci/kcptun/server/main.go:84 +0x2ae

goroutine 28 [IO wait]:
internal/poll.runtime_pollWait(0x7ff74cac1eb0, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4200f4918, 0x72, 0xffffffffffffff00, 0x9ebf40, 0x9e8340)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc4200f4918, 0xc4201c2000, 0x8000, 0x8000)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4200f4900, 0xc4201c2000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc4200f4900, 0xc4201c2000, 0x8000, 0x8000, 0x22, 0xc420022680, 0x443537)
        /usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42000c0a0, 0xc4201c2000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:176 +0x6d
io.copyBuffer(0x7ff74cac6360, 0xc4200f6240, 0x7ff74cac6388, 0xc42000c0a0, 0xc4201c2000, 0x8000, 0x8000, 0x7f7540, 0xc420022700, 0x7ff74cac6388)
        /usr/local/go/src/io/io.go:392 +0x123
io.Copy(0x7ff74cac6360, 0xc4200f6240, 0x7ff74cac6388, 0xc42000c0a0, 0xc42000c0a0, 0x738a3d, 0x1)
        /usr/local/go/src/io/io.go:362 +0x68
main.handleClient.func1(0x9eee00, 0xc4200f6240, 0x7ff74cac6288, 0xc42000c0a0, 0xc420054ea0)
        /Users/xtaci/src/github.com/xtaci/kcptun/server/main.go:96 +0xa9
created by main.handleClient
        /Users/xtaci/src/github.com/xtaci/kcptun/server/main.go:96 +0x1bb

goroutine 29 [select]:
github.com/xtaci/smux.(*Stream).Read(0xc4200f6240, 0xc4201ba000, 0x8000, 0x8000, 0x0, 0x9e9dc0, 0xc420044040)
        /Users/xtaci/src/github.com/xtaci/smux/stream.go:67 +0x330
io.copyBuffer(0x9eb580, 0xc4200451d0, 0x7ff74cac62c0, 0xc4200f6240, 0xc4201ba000, 0x8000, 0x8000, 0xc4200451d0, 0xc4200451d0, 0x7b3800)
        /usr/local/go/src/io/io.go:392 +0x123
io.Copy(0x9eb580, 0xc4200451d0, 0x7ff74cac62c0, 0xc4200f6240, 0x7f7578, 0xc420022e50, 0x40d925)
        /usr/local/go/src/io/io.go:362 +0x68
net.genericReadFrom(0x9ea280, 0xc42000c0a0, 0x7ff74cac62c0, 0xc4200f6240, 0x0, 0x0, 0x7ed100)
        /usr/local/go/src/net/net.go:595 +0x84
net.(*TCPConn).readFrom(0xc42000c0a0, 0x7ff74cac62c0, 0xc4200f6240, 0x7ff74cac6310, 0xc420022e80, 0x40ef9d)
        /usr/local/go/src/net/tcpsock_posix.go:51 +0xa5
net.(*TCPConn).ReadFrom(0xc42000c0a0, 0x7ff74cac62c0, 0xc4200f6240, 0x7ff74cac6310, 0xc42000c0a0, 0x36c01000001)
        /usr/local/go/src/net/tcpsock.go:103 +0x5f
io.copyBuffer(0x9ea280, 0xc42000c0a0, 0x7ff74cac62c0, 0xc4200f6240, 0x0, 0x0, 0x0, 0x7ed1c0, 0x0, 0x7ff74cac62c0)
        /usr/local/go/src/io/io.go:386 +0x2bb
io.Copy(0x9ea280, 0xc42000c0a0, 0x7ff74cac62c0, 0xc4200f6240, 0xc4200f6240, 0x0, 0xc420054660)
        /usr/local/go/src/io/io.go:362 +0x68
main.handleClient.func2(0x7ff74cac6288, 0xc42000c0a0, 0x9eee00, 0xc4200f6240, 0xc420054f00)
        /Users/xtaci/src/github.com/xtaci/kcptun/server/main.go:99 +0xa9
created by main.handleClient
        /Users/xtaci/src/github.com/xtaci/kcptun/server/main.go:99 +0x22f

rax    0x5c2
rbx    0xc42001381a
rcx    0x270
rdx    0xc42012b81a
rdi    0xc42012b81a
rsi    0x0
rbp    0xc42003da70
rsp    0xc42003d9e0
r8     0x0
r9     0x20
r10    0xc42008d000
r11    0x3c0
r12    0x270
r13    0xc42001381a
r14    0x0
r15    0x0
rip    0x71850f
rflags 0x10246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by xtaci** [comment]
@templexxx

**Comment by IndeedPlusPlus** [comment]
I dug around and found out that
[templexxx/reedsolomon@979895f353956b192c1bce48347c626d9328ec20](https://github.com/templexxx/reedsolomon/commit/979895f353956b192c1bce48347c626d9328ec20) seems to fix this issue.

**Comment by IndeedPlusPlus** [comment]
related templexxx/reedsolomon#6

and #504

**Comment by IndeedPlusPlus** [comment]
Since all patches are ready, I suggest a new version be released to address this issue.

**Comment by templexxx** [comment]
@IndeedPlusPlus I think https://github.com/templexxx/reedsolomon it's ok now, could you run the test on your machine?

**Comment by IndeedPlusPlus** [comment]
@templexxx I can confirm templexxx/reedsolomon@979895f353956b192c1bce48347c626d9328ec20 fixes this problem. I rebuilt with HEAD version of templexxx/reedsolomon and found no issue.

**Comment by templexxx** [comment]
@IndeedPlusPlus that's cool. Thank you for your job~

**Comment by xtaci** [comment]
@templexxx notify me if you tagged a new release

**Comment by xtaci** [comment]
seems to be fixed
