### ISSUE TITLE
20191105mac客户端运行一段时间后出错

### ISSUE THREAD

**Issue by maxwellzh** [xtaci/kcptun#734]
```
panic: runtime error: slice bounds out of range [:70] with capacity 0

goroutine 48863 [running]:
github.com/xtaci/kcp-go.(*UDPSession).output(0xc00007e1a0, 0xc00060c580, 0x46, 0x546)
        /Users/xtaci/go/pkg/mod/github.com/xtaci/kcp-go@v5.4.17+incompatible/sess.go:565 +0x80f
github.com/xtaci/kcp-go.newUDPSession.func1(0xc00060c580, 0x546, 0x546, 0x46)
        /Users/xtaci/go/pkg/mod/github.com/xtaci/kcp-go@v5.4.17+incompatible/sess.go:172 +0x5d
github.com/xtaci/kcp-go.(*KCP).flush.func2(...)
        /Users/xtaci/go/pkg/mod/github.com/xtaci/kcp-go@v5.4.17+incompatible/kcp.go:685
github.com/xtaci/kcp-go.(*KCP).flush(0xc0000ac120, 0xc0001a0000, 0x12)
        /Users/xtaci/go/pkg/mod/github.com/xtaci/kcp-go@v5.4.17+incompatible/kcp.go:842 +0xb32
github.com/xtaci/kcp-go.(*UDPSession).WriteBuffers(0xc00007e1a0, 0xc00007bcf0, 0x1, 0x1, 0xc000190000, 0x8, 0x10000)
        /Users/xtaci/go/pkg/mod/github.com/xtaci/kcp-go@v5.4.17+incompatible/sess.go:296 +0x8cd
github.com/xtaci/kcp-go.(*UDPSession).Write(0xc00007e1a0, 0xc0001a0000, 0x12, 0x12adc, 0x0, 0x0, 0xc0001a0012)
        /Users/xtaci/go/pkg/mod/github.com/xtaci/kcp-go@v5.4.17+incompatible/sess.go:263 +0x7a
github.com/golang/snappy.(*Writer).write(0xc0002e0060, 0x0, 0x0, 0x0, 0x8, 0xc00020ac00, 0x0)
        /Users/xtaci/go/pkg/mod/github.com/golang/snappy@v0.0.1/encode.go:249 +0x31e
github.com/golang/snappy.(*Writer).Flush(0xc0002e0060, 0xc0002c4000, 0x8)
        /Users/xtaci/go/pkg/mod/github.com/golang/snappy@v0.0.1/encode.go:272 +0x6e
github.com/xtaci/kcptun/generic.(*CompStream).Write(0xc000b86000, 0xc0002c4000, 0x8, 0x10008, 0x1, 0xc000b76e00, 0x8000)
        /Users/xtaci/go/src/github.com/xtaci/kcptun/generic/comp.go:26 +0x11d
github.com/xtaci/smux.(*Session).sendLoop(0xc000918100)
        /Users/xtaci/go/pkg/mod/github.com/xtaci/smux@v1.4.4/session.go:446 +0x56c
created by github.com/xtaci/smux.newSession
        /Users/xtaci/go/pkg/mod/github.com/xtaci/smux@v1.4.4/session.go:105 +0x2b1
```
windows和linux客户端待观察

**Comment by maxwellzh** [comment]
客户端配置
```
2019/11/05 18:02:39 version: 20191105
2019/11/05 18:02:39 smux version: 1
2019/11/05 18:02:39 listening on: [::]:9810
2019/11/05 18:02:39 encryption: none
2019/11/05 18:02:39 nodelay parameters: 1 10 2 1
2019/11/05 18:02:39 remote address: [ipv6 address]:9500
2019/11/05 18:02:39 sndwnd: 128 rcvwnd: 512
2019/11/05 18:02:39 compression: true
2019/11/05 18:02:39 mtu: 1350
2019/11/05 18:02:39 datashard: 10 parityshard: 3
2019/11/05 18:02:39 acknodelay: false
2019/11/05 18:02:39 dscp: 0
2019/11/05 18:02:39 sockbuf: 4194304
2019/11/05 18:02:39 smuxbuf: 4194304
2019/11/05 18:02:39 streambuf: 2097152
2019/11/05 18:02:39 keepalive: 10
2019/11/05 18:02:39 conn: 1
2019/11/05 18:02:39 autoexpire: 10
2019/11/05 18:02:39 scavengettl: 600
2019/11/05 18:02:39 snmplog: 
2019/11/05 18:02:39 snmpperiod: 60
2019/11/05 18:02:39 quiet: true
2019/11/05 18:02:39 tcp: false
2019/11/05 18:02:39 initiating key derivation
2019/11/05 18:02:39 key derivation done
2019/11/05 18:02:39 smux version: 1 on connection: [::]:64958 -> [ipv6 address]:9500
```

**Comment by xtaci** [comment]
嗯，奇怪， sync.Pool.Put(nil)我看golang代码是处理过的

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/releases/tag/v20191105
重新上传了

**Comment by maxwellzh** [comment]
ok，先用一段时间再来反馈

**Comment by maxwellzh** [comment]
linux/windows/mac目前看来应该没问题了:thumbsup:
