### ISSUE TITLE
ar71xx mips无法运行最新版本(20200226)客户端

### ISSUE THREAD

**Issue by zhanhb** [xtaci/kcptun#753]
问问题前先搜索ISSUE，并搞清楚下面的问题:
感觉有可能是go1.14编译出的文件和这个系统不兼容，或许需要增加编译参数

8. 是不是最新版本？ 是
9. 两端分别是什么操作系统？客户端 mips ar71xx
10. 两端的输出日志是什么？

运行日志：
```txt
SIGILL: illegal instruction
PC=0x886cc m=0 sigcode=128

goroutine 1 [running, locked to thread]:
runtime.asyncPreempt()
	/usr/local/go/src/runtime/preempt_mipsx.s:40 +0x7c fp=0x145af64 sp=0x145ae70 pc=0x886cc
github.com/google/gopacket/layers.initUnknownTypesForEthernetType()
	/home/xtaci/go/pkg/mod/github.com/google/gopacket@v1.1.17/layers/enums_generated.go:96 +0xc0 fp=0x145af80 sp=0x145af68 pc=0x2891a4
github.com/google/gopacket/layers.init.0()
	/home/xtaci/go/pkg/mod/github.com/google/gopacket@v1.1.17/layers/enums_generated.go:16 +0x3c fp=0x145af84 sp=0x145af80 pc=0x288b68
runtime.doInit(0x6934e0)
	/usr/local/go/src/runtime/proc.go:5414 +0xcc fp=0x145af98 sp=0x145af84 pc=0x5f968
runtime.doInit(0x693060)
	/usr/local/go/src/runtime/proc.go:5409 +0x80 fp=0x145afac sp=0x145af98 pc=0x5f91c
runtime.doInit(0x693ae0)
	/usr/local/go/src/runtime/proc.go:5409 +0x80 fp=0x145afc0 sp=0x145afac pc=0x5f91c
runtime.main()
	/usr/local/go/src/runtime/proc.go:190 +0x22c fp=0x145afec sp=0x145afc0 pc=0x5013c
runtime.goexit()
	/usr/local/go/src/runtime/asm_mipsx.s:651 +0x4 fp=0x145afec sp=0x145afec pc=0x87f4c

goroutine 6 [select]:
github.com/xtaci/kcp-go/v5.(*TimedSched).sched(0x1448060)
	/home/xtaci/go/pkg/mod/github.com/xtaci/kcp-go/v5@v5.5.8/timedsched.go:66 +0x348
created by github.com/xtaci/kcp-go/v5.NewTimedSched
	/home/xtaci/go/pkg/mod/github.com/xtaci/kcp-go/v5@v5.5.8/timedsched.go:56 +0x118

goroutine 7 [select]:
github.com/xtaci/kcp-go/v5.(*TimedSched).prepend(0x1448060)
	/home/xtaci/go/pkg/mod/github.com/xtaci/kcp-go/v5@v5.5.8/timedsched.go:98 +0x2c8
created by github.com/xtaci/kcp-go/v5.NewTimedSched
	/home/xtaci/go/pkg/mod/github.com/xtaci/kcp-go/v5@v5.5.8/timedsched.go:58 +0x154

r0   0x0	r1   0x4
r2   0x143e	r3   0x18
r4   0x9ecd20	r5   0x705650
r6   0x6e7080	r7   0x480000
```

**Comment by xtaci** [comment]
嗯，如果miple/be没选错，那就是golang1.14的问题了

**Comment by sotux** [comment]
1.14 是有问题。我在 OpenWrt  上用 go 1.14 编译的 mt7621 mipsle 平台运行也有问题。

**Comment by nebulabox** [comment]
遇到同样问题。go 1.14编译的 mipsle 有问题

**Comment by xtaci** [comment]
https://github.com/golang/go/issues/37667
golang官方知晓

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/releases/tag/v20200321
